INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ABRD', 'АбрауДюрсо');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AFKS', 'Система ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AFLT', 'Аэрофлот');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AGRO', 'AGRO-гдр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AKRN', 'Акрон');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ALBK', 'БестЭфБ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ALNU', 'АЛРОСА-Нюр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ALRS', 'АЛРОСА ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AMEZ', 'АшинскийМЗ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('APTK', 'Аптеки36и6');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AQUA', 'РусАква ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ARSA', 'Арсагера');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ASSB', 'АстрЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('AVAN', 'Авангрд-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BANE', 'Башнефт ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BANEP', 'Башнефт ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BELU', 'Белуга ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BISV', 'БашИнСв ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BISVP', 'БашИнСв ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BLNG', 'Белон ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BRZL', 'БурЗолото');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('BSPB', 'БСП ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CBOM', 'МКБ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CHEP', 'ЧТПЗ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CHGZ', 'РН-ЗапСиб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CHKZ', 'ЧКПЗ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CHMF', 'СевСт-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CHMK', 'ЧМК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CNTL', 'Телеграф');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('CNTLP', 'Телеграф-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('DASB', 'ДагСб ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('DIOD', 'ЗаводДИОД');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('DSKY', 'ДетскийМир');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('DVEC', 'ДЭК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('DZRD', 'iДонскЗР');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('DZRDP', 'iДонскЗР п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('EELT', 'ЕвроЭлтех');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ELTZ', 'Электрцинк');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ENPG', 'ЭН+ГРУП ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ENRU', 'ЭнелРос ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ETLN', 'ETLN-гдр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('FEES', 'ФСК ЕЭС ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('FESH', 'ДВМП ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('FIVE', 'FIVE-гдр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GAZA', 'ГАЗ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GAZAP', 'ГАЗ ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GAZC', 'ГАЗКОН-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GAZP', 'ГАЗПРОМ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GAZS', 'ГАЗ-сервис');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GAZT', 'ГАЗ-Тек ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GCHE', 'ЧеркизГ-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GEMA', 'iММЦБ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GMKN', 'ГМКНорНик');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GTRK', 'ГТМ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('GTSS', 'ГЕОТЕК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('HALS', 'Галс-Девел');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('HIMC', 'Химпром ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('HIMCP', 'Химпром ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('HYDR', 'РусГидро');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('IGST', 'Ижсталь2ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('IGSTP', 'Ижсталь ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('INGR', 'ИНГРАД ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('IRAO', 'ИнтерРАОао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('IRGZ', 'ИркЭнерго');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('IRKT', 'ИРКУТ-3');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ISKJ', 'iИСКЧ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('JNOS', 'Славн-ЯНОС');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('JNOSP', 'Слав-ЯНОСп');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KAZT', 'Куйбазот');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KAZTP', 'Куйбазот-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KBSB', 'ТНСэКубань');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KBTK', 'КузбТК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KCHE', 'КамчатЭ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KCHEP', 'КамчатЭ ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KGKC', 'КурганГКао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KGKCP', 'КурганГКап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KLSB', 'КалужскСК');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KMAZ', 'КАМАЗ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KMEZ', 'КМЗ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KMTZ', 'КосогМЗ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KOGK', 'КоршГОК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KRKN', 'СаратНПЗ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KRKNP', 'СаратНПЗ-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KRKO', 'ТКЗКК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KRKOP', 'ТКЗКК ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KROT', 'КрасОкт-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KROTP', 'КрасОкт-1п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KRSB', 'Красэсб ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KRSBP', 'Красэсб ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KSGR', 'Кокс ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KTSB', 'КСБ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KTSBP', 'КСБ ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KUBE', 'Кубанэнр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KUNF', 'КУЗОЦМ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KUZB', 'КузнецкийБ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KZMS', 'КЗМС ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KZOS', 'ОргСинт ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('KZOSP', 'ОргСинт ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LIFE', 'iФармсинтз');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LKOH', 'ЛУКОЙЛ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LNTA', 'Лента др');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LNZL', 'Лензолото');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LNZLP', 'Лензол. ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LPSB', 'ЛЭСК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LSNG', 'Ленэнерго');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LSNGP', 'Ленэнерг-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LSRG', 'ЛСР ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('LVHK', 'Левенгук');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MAGE', 'МагадЭн ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MAGEP', 'МагадЭн ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MAGN', 'ММК');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MAIL', 'MAIL-гдр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MFGS', 'Мегион-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MFGSP', 'Мегион-ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MFON', 'МегаФон ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MGNT', 'Магнит ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MGNZ', 'СМЗ-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MGTS', 'МГТС-5ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MGTSP', 'МГТС-4ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MISB', 'ТНСэнМарЭл');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MISBP', 'ТНСэМаЭл-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MOBB', 'МосОблБанк');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MOEX', 'МосБиржа');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MORI', 'Морион ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKC', 'МРСК Центр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKK', 'Россети СК');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKP', 'МРСК ЦП');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKS', 'МРСКСиб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKU', 'МРСК Ур');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKV', 'МРСКВол');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKY', 'РоссЮг ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRKZ', 'МРСК СЗ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MRSB', 'МордЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MSNG', '+МосЭнерго');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MSRS', 'РСетиМР ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MSTT', 'Мостотрест');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MTLR', 'Мечел ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MTLRP', 'Мечел ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MTSS', 'МТС-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('MVID', 'М.видео');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NAUK', 'iНПОНаука');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NFAZ', 'Нефтекамск');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NKHP', 'НКХП ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NKNC', 'НКНХ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NKNCP', 'НКНХ ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NKSH', 'Нижкамшина');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NLMK', 'НЛМК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NMTP', 'НМТП ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NNSB', 'ТНСэнНН ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NNSBP', 'ТНСэнНН ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NPOF', 'Физика ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NSVZ', 'НаукаСвяз');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('NVTK', 'Новатэк ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('OBUV', 'ОР ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('OGKB', 'ОГК-2 ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('OMZZP', 'ОМЗ-ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PAZA', 'ПавлАвт ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PHOR', 'ФосАгро ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PIKK', 'ПИК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PLZL', 'Полюс');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PMSB', 'ПермьЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PMSBP', 'ПермьЭнС-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('POGR', 'Petropavl');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('POLY', 'Polymetal');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PRMB', 'Приморье');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('PRTK', 'ПРОТЕК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('QIWI', 'iQIWI');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RASP', 'Распадская');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RAVN', 'Raven');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RBCM', 'РБК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RDRB', 'РДБанк ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RGSS', 'РГС СК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RKKE', 'ЭнергияРКК');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RLMN', 'Роллман');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RLMNP', 'Роллман-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RNFT', 'РуссНфт ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ROLO', 'Русолово');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ROSB', 'Росбанк ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ROSN', 'Роснефть');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ROST', 'РОСИНТЕРао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RSTI', 'Россети ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RSTIP', 'Россети ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RTGZ', 'ГазпРнД ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RTKM', 'Ростел -ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RTKMP', 'Ростел -ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RTSB', 'ТНСэнРст');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RTSBP', 'ТНСэнРст-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RUAL', 'RUSAL plc');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RUGR', 'Русгрэйн');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RUSI', 'ИКРУСС-ИНВ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RUSP', 'Русполимет');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('RZSB', 'РязЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SAGO', 'СамарЭн-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SAGOP', 'СамарЭн-ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SARE', 'СаратЭн-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SAREP', 'СаратЭн-ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SBER', 'Сбербанк');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SBERP', 'Сбербанк-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SELG', 'Селигдар');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SELGP', 'Селигдар-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SFIN', 'САФМАР ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SIBN', 'Газпрнефть');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SLEN', 'Сахэнер ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SNGS', 'Сургнфгз');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SNGSP', 'Сургнфгз-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('STSB', 'СтаврЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('STSBP', 'СтаврЭнСбп');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('SVAV', 'СОЛЛЕРС');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TASB', 'ТамбЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TASBP', 'ТамбЭнСб-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TATN', 'Татнфт 3ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TATNP', 'Татнфт 3ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TCSG', 'TCS-гдр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TGKA', 'ТГК-1');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TGKB', 'ТГК-2');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TGKBP', 'ТГК-2 ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TGKD', 'Квадра');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TGKDP', 'Квадра-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TGKN', 'ТГК-14');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TNSE', 'ТНСэнрг ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TORS', 'ТРК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TORSP', 'ТРК ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TRCN', 'ТрансК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TRFM', 'ТрансФ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TRMK', 'ТМК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TRNFP', 'Транснф ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TTLK', 'Таттел. ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('TUZA', 'ТЗА ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UCSS', 'ОКС ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UKUZ', 'ЮжКузб. ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UNAC', 'iАвиастКао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UNKL', 'ЮУНК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UPRO', 'Юнипро ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('URKA', 'Уркалий-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('URKZ', 'УрКузница');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('USBN', 'УралСиб ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UTAR', 'ЮТэйр ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('UWGN', 'ОВК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VGSB', 'ВолгЭнСб');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VGSBP', 'ВолгЭнСб-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VJGZ', 'Варьеган');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VJGZP', 'Варьеган-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VLHZ', 'ВХЗ-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VRSB', 'ТНСэнВорон');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VRSBP', 'ТНСэнВор-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VSMO', 'ВСМПО-АВСМ');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VSYD', 'ВыбСудЗ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VSYDP', 'ВыбСудЗ ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VTBR', 'ВТБ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VZRZ', 'Возрожд-ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('VZRZP', 'Возрожд-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('WTCM', 'ЦМТ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('WTCMP', 'ЦМТ ап');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('YAKG', 'ЯТЭК ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('YKEN', 'Якутскэнрг');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('YKENP', 'Якутскэн-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('YNDX', 'Yandex clA');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('YRSB', 'ТНСэнЯр');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('YRSBP', 'ТНСэнЯр-п');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ZILL', 'ЗИЛ ао');
INSERT INTO moex_webdb.security (SECID, SHORTNAME) VALUES ('ZVEZ', 'ЗВЕЗДА ао');